"""Add NMR stability field

Revision ID: 0e7074cdbb6a
Revises: 15eac5729a8d
Create Date: 2026-09-29 10:14:20.082551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7074cdbb6a'
down_revision = '15eac5729a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stability', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.drop_column('stability')

    # ### end Alembic commands ###
