"""Update NMR Sample models

Revision ID: 46d2f6acd7f3
Revises: da7cc0e894fc
Create Date: 2026-09-29 10:59:20.967918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d2f6acd7f3'
down_revision = 'da7cc0e894fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.alter_column('solvent',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('experiments',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.alter_column('experiments',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('solvent',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
