"""Use int to store NMR stability

Revision ID: 500759b95838
Revises: 0e7074cdbb6a
Create Date: 2026-09-29 10:23:00.299485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500759b95838'
down_revision = '0e7074cdbb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.alter_column('stability',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.alter_column('stability',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
