"""empty message

Revision ID: 522250902ec6
Revises: 
Create Date: 2026-09-30 18:16:25.741897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522250902ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('teams', sa.String(length=100), nullable=True),
    sa.Column('last_team_used', sa.String(length=5), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('analysis_type', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('structure_file', sa.String(length=500), nullable=True),
    sa.Column('formula', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('mass_spectrum', sa.String(length=500), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('formula', sa.String(length=100), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solvents', sa.String(length=100), nullable=True),
    sa.Column('other_solvent', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nmr_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('solvent', sa.String(length=10), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('experiments', sa.String(length=200), nullable=True),
    sa.Column('other_experiment', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nmr_samples')
    op.drop_table('ms_samples')
    op.drop_table('analyses')
    op.drop_table('samples')
    op.drop_table('users')
    # ### end Alembic commands ###
