"""add local users functionnality

Revision ID: 64ae5cba2ca8
Revises: ea7a8aa3e271
Create Date: 2026-10-07 14:55:50.152563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ae5cba2ca8'
down_revision = 'ea7a8aa3e271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_ldap', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_ldap')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
