"""Alter Analysis

Revision ID: 9c61c823abf5
Revises: 64ae5cba2ca8
Create Date: 2026-10-08 16:05:34.394105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c61c823abf5'
down_revision = '64ae5cba2ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_file', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('results_file', sa.String(length=500), nullable=True))
        batch_op.drop_column('results')
        batch_op.drop_column('mass_spectrum')
        batch_op.drop_column('molecular_weight')
        batch_op.drop_column('formula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('molecular_weight', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('mass_spectrum', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('results', sa.TEXT(), nullable=True))
        batch_op.drop_column('results_file')
        batch_op.drop_column('data_file')

    # ### end Alembic commands ###
