"""Add sample formula

Revision ID: be43f74b9fe8
Revises: 45d5ed369b23
Create Date: 2026-09-27 17:09:52.481611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be43f74b9fe8'
down_revision = '45d5ed369b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.String(length=100), nullable=True))
        batch_op.alter_column('structure_file',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('structure_file',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('formula')

    # ### end Alembic commands ###
