"""Use int to store instrument frequency

Revision ID: da7cc0e894fc
Revises: 500759b95838
Create Date: 2026-09-29 10:25:51.983716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7cc0e894fc'
down_revision = '500759b95838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nmr_samples', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
