"""Add smiles and mass field for Sample

Revision ID: ea7a8aa3e271
Revises: 522250902ec6
Create Date: 2026-10-03 20:27:36.517014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7a8aa3e271'
down_revision = '522250902ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smiles', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_column('mass')
        batch_op.drop_column('smiles')

    # ### end Alembic commands ###
